makemigration:
    python manage.py makemigration

# Start the Django development server
runserver:
    python manage.py runserver

# Combined target: Apply migrations and then start the server
migrate: python manage.py migrate